version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3307:3306
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./mariadb-config:/etc/mysql